### ISSUE TITLE
Please check if the default date is always set on iOS

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-frontend#13] opened 2021-05-27 11:44 UTC
**Describe the bug**
When using the DateTimePicker on iOS, the initial value is the current date. But, if the user doesn't change it, the value is not set in the questionnaireItemMap.

**To Reproduce**
1. Go to the default questionnaire, first page
2. Click on always on next, fill in empty values, but do not touch the DateTimePicker
3. Try to submit the questionnaire, it is not possible because the date is not set in the questionnaireItemMap (but the item is required), even though it looks to the user like it is set.

**Expected behavior**
The default date of the slider is incorporated into the normal state.

**Screenshots**

**Smartphone (please complete the following information):**
- iOS Emulator

**Additional context**
An open question is, how the android behaviour should be. By looking at the source code, it looks to me like Android supports also empty dates. There should be a unique behaviour on both platforms, preferably one where it is possible to omit dates.

**Comment by mbastian93** [comment] 2021-05-28 07:37
In my opinion, the preferred behavior shouldn't be to use a default date, but to make it clearer to the user, that a date hasn't actively been chosen yet as in many (most?) cases the default date ("today") is not the correct one.

**Comment by JohannesOehm** [comment] 2021-05-28 07:59
@mbastian93 I agree. Maybe it's best to render the same textfield on iOS as on Android and create then an window or modal containing the DateTimePicker component from iOS.

**Comment by mbastian93** [comment] 2021-06-08 12:57
Even when implemented similarly to android, the ios datepicker has no "confirm" button to accept the (pre-selected) date, no matter if the spinner or the dialog variant is used. Therefore no change event occurs and the answer is not set, so ultimately the behavior wouldn't really change.

Since the current date ("today") is rarely the correct one, I suggest to close this for now.

**Comment by JohannesOehm** [comment] 2021-06-08 13:23
What do you mean by close this for now? In some cases, the current date is the correct one, so the user might not want to change this and relies on the value being stort as default. Also, because a date item might be required, the internal validation fails, but the user thinks he has already entered all the necessary information.

Can't someone just build a dialog with the date spinner and "OK" and "Abort" buttons for iOS? Then, clicking OK triggers the event, and clicking Abort leaves the text field blank. I'm not an expert in React Native but it shouldn't be that hard.

**Comment by GolexPrime** [comment] 2021-06-08 16:33
The modal utilizing the datepicker is working as originally designed.
The current date is pre-selected but not confirmed. Thats indicated by the color of the button at the bottom of the modal. If a valid value is set, the button turns green (or whatever color is defined in the configuration file). If the datepicker is not touched, then the internal validation will render the questionnaire incomplete, thus preventing the user from transmitting it.

The OK-Button approach was originally also implemented but later removed due to "design concerns". Of course, this behaviour can be changed in the future - if the community agrees that the usability needs to be improved. Thats whats discussions are for. But I would not classify it as a bug.

**Comment by GolexPrime** [comment] 2021-06-10 07:35
No more comments? Excellent. I'll close the issue then.
Please feel free to create a new one with recommendations for usability improvements.

**Closed by GolexPrime** 2021-06-10 07:35 UTC
Labels: bug

**Comment by JohannesOehm** [comment] 2021-06-10 08:00
Yes, probably its not a bug, but still very confusing. I created a feature request. Thank you!
